In [6]:
import numpy as np

ar=np.array([1,2,23,40])
ar
type(ar)

# Why Use NumPy?
# In Python we have lists that serve the purpose of arrays, but they are slow to process.

# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

numpy.ndarray

In [7]:
#checking numpy version
print(np.__version__)

1.25.1


In [9]:
# use a tuple to create numpy arrays
myar2=np.array((1,2,5,8,9))
myar2

array([1, 2, 5, 8, 9])

In [20]:
#array dimensions
# o-d arrays
a=np.array(1)
a
print(type(a))
#2-d arrays
b=np.array([[1,2,3,4],["a","b","c","d"]])
b

<class 'numpy.ndarray'>


array([['1', '2', '3', '4'],
       ['a', 'b', 'c', 'd']], dtype='<U11')

In [41]:
#3-d array
c=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
c

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [44]:
#check number of dimensions

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [45]:
a=np.array([5])
print(a.ndim)

1


In [49]:
b=np.array([[5],[10]])
print(b.ndim)

2


In [50]:
c=np.array([[[1],[2],[3]]])
print(c.ndim)

3


In [59]:
# create an array with 5 dimensions
d=np.array([1,2,3,4],ndmin=5)
print(d)
print('number of dimensions :', d.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [60]:
# now i will play with array indexing
e=np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [95]:


f=np.array([[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]]])
f.ndim
print(f,f.ndim)


[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]]]] 5


In [113]:
f[0]

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [114]:
# array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [115]:
print(arr[0:])

[1 2 3 4 5 6 7]


In [117]:
print(arr[0:4])

[1 2 3 4]


In [118]:
# negative inexing
print(arr[:-1])

[1 2 3 4 5 6]


In [119]:
# stepping
arr[0:5:2]

array([1, 3, 5])

In [122]:
# slicing 2d arrays
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2[0, 1:4])

[2 3 4]


In [123]:
# getting array data type
arr3=np.array([1,2,3,4])
print(arr3.dtype)

int32


In [128]:
arr4=np.array(["anand","avinash","amar",'ajay',"anant","aryan","avani"])
print(arr4.dtype)

<U7


In [131]:
# converting data type of existing an array
newarr=arr4.astype('S')
print(newarr,newarr.dtype)

[b'anand' b'avinash' b'amar' b'ajay' b'anant' b'aryan' b'avani'] |S7


In [132]:
arr5=np.array([1,0,2])
newarr2=arr5.astype('b')

In [133]:
print(newarr2)

[1 0 2]


In [138]:
# difference between copy and view
a1=np.array([0,1,2,3,4])
b1=a1.copy()
b1[0]=52
b1[1]=62
print(a1,b1)
c1=a1.view()
print(a1,b1,c1)
# Print the value of the base attribute to check if an array owns it's data or not:
print(a1.base,b1.base,c1.base)

[0 1 2 3 4] [52 62  2  3  4]
[0 1 2 3 4] [52 62  2  3  4] [0 1 2 3 4]
None None [0 1 2 3 4]


In [141]:
# shape of an array
print(a1.shape)

(5,)


In [143]:
# reshape of an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [157]:
newarr5=arr.reshape(4,3)
print(newarr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [158]:
# numpy array iterating
for i in newarr5:
    print(i)


[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [174]:
# playing with nd array
a10 = np.array([[[[1, 2, 3], [4, 5, 6],[7,8,9],[10,11,12]]]])
print(a10.ndim)
# a10
for i in a10:
    for j in i:
        for k in j:
            for l in k:
                print(l)

4
1
2
3
4
5
6
7
8
9
10
11
12


In [175]:
# iterating array using nditer
arr11 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr11):
  print(x)

1
2
3
4
5
6
7
8


In [176]:
# array concatenating
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
